/** Metadata for CFG-* drawing prefixes (must stay aligned with scripts/upload_shop_drawings.py). */
export type PrefixMeta = {
  dims: 1 | 2 | 3;
  /** When dims===3 and true, the third numeric segment is roof pitch (deg). */
  hasPitch: boolean;
};

export const PREFIX_META: Record<string, PrefixMeta> = {
  "CFG-MR": { dims: 3, hasPitch: true },
  "CFG-CR": { dims: 2, hasPitch: false },
  "CFG-S1-MR": { dims: 3, hasPitch: true },
  "CFG-S3-MR": { dims: 3, hasPitch: true },
  "CFG-MR-LV": { dims: 3, hasPitch: true },
  "CFG-S1-MR-SD": { dims: 3, hasPitch: true },
  "CFG-MR-GR": { dims: 3, hasPitch: true },
  "CFG-S3-MR-GR": { dims: 3, hasPitch: true },
  "CFG-S2-CR": { dims: 2, hasPitch: false },
  "CFG-ES-SD": { dims: 2, hasPitch: false },
  "CFG-S3-MR-SD": { dims: 3, hasPitch: true },
  "CFG-MR-A+R": { dims: 3, hasPitch: true },
  "CFG-A+CON": { dims: 1, hasPitch: false },
  "CFG-MR-A+": { dims: 3, hasPitch: true },
  "CFG-CUS": { dims: 3, hasPitch: true },
  "CFG-S1-MR-GR": { dims: 3, hasPitch: true },
  "CFG-MR-OR": { dims: 3, hasPitch: true },
  "CFG-MR-ARF": { dims: 3, hasPitch: true },
  "CFG-LV-STL": { dims: 1, hasPitch: false },
  "CFG-S3-MR-LW": { dims: 3, hasPitch: true },
  "CFG-S1-CR-R": { dims: 2, hasPitch: false },
  "CFG-SP-GR": { dims: 3, hasPitch: true },
  "CFG-CR-A+": { dims: 2, hasPitch: false },
  "CFG-CR-AL": { dims: 2, hasPitch: false },
  "CFG-MR-AL": { dims: 3, hasPitch: true },
  "CFG-CR-CA": { dims: 2, hasPitch: false },
  "CFG-MR-CA": { dims: 3, hasPitch: true },
  "CFG-VLV-CON": { dims: 1, hasPitch: false },
  "CFG-MR-GT": { dims: 3, hasPitch: true },
  "CFG-ES-SUN": { dims: 3, hasPitch: false },
  "CFG-RR-GR": { dims: 3, hasPitch: true },
  "CFG-S1-MR-LW": { dims: 3, hasPitch: true },
  "CFG-S1-MR-GD": { dims: 3, hasPitch: true },
  "CFG-S3-MR-A+": { dims: 3, hasPitch: true },
  "CFG-S2-CR-LW": { dims: 2, hasPitch: false },
  "CFG-S2-CR-SDSS": { dims: 2, hasPitch: false },
  "CFG-CR-LV": { dims: 2, hasPitch: false },
  "CFG-LV-CON": { dims: 2, hasPitch: false },
  "CFG-TCR": { dims: 2, hasPitch: false },
  "CFG-LV-PR": { dims: 2, hasPitch: false },
  "CFG-LV-FR": { dims: 2, hasPitch: false },
  "CFG-CT": { dims: 3, hasPitch: true },
  "CFG-ES-LW": { dims: 2, hasPitch: false },
  "CFG-VUW-CON": { dims: 2, hasPitch: false },
  "CFG-ES": { dims: 2, hasPitch: false },
};
